курсач/NTCService/NTCService/Models/ModelDB/NTCWorkers.cs
namespace NTCService
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class NTCWorkers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NTCWorkers()
        {
            NTCJournal = new HashSet<NTCJournal>();
        }

        [Key]
        public int id_NTCworker { get; set; }

        [StringLength(50)]
        public string name_NTCworker { get; set; }

        [StringLength(30)]
        public string phone_number_NTCworker { get; set; }

        [StringLength(50)]
        public string email_NTCworker { get; set; }

        [StringLength(50)]
        public string skype_NTCworker { get; set; }

        public int? experience { get; set; }

        public int? salary { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NTCJournal> NTCJournal { get; set; }
    }
}

курсач/NTCService/NTCService/Controllers/NTCWorkersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NTCService;
using PagedList;

namespace NTCService.Controllers
{
    [Authorize(Roles = "Admin")]

    //Клас EquipmentTypesController - для роботи з працівниками
    public class NTCWorkersController : Controller
    {
        private ModelDB db = new ModelDB();

        //Action для сторінки зі списком працівників
        public ActionResult Index(string sortOrder, string SearchByName, string SearchByNumb, string SearchByMail, string SearchBySkype,
                    string currentFilter, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.PhoneNumbSortParm = sortOrder == "phone_numb" ? "phone_numb_desc" : "phone_numb";
            ViewBag.EmailSortParm = sortOrder == "email" ? "email_desc" : "email";
            ViewBag.SkypeSortParm = sortOrder == "skype" ? "skype_desc" : "skype";
            ViewBag.ExperienceSortParm = sortOrder == "experience" ? "experience_desc" : "experience";
            ViewBag.SalarySortParm = sortOrder == "salary" ? "salary_desc" : "salary";

            if (SearchByName != null)
            {
                page = 1;
            }
            else
            {
                SearchByName = currentFilter;
            }

            if (SearchByNumb != null)
            {
                page = 1;
            }
            else
            {
                SearchByNumb = currentFilter;
            }

            if (SearchByMail != null)
            {
                page = 1;
            }
            else
            {
                SearchByMail = currentFilter;
            }

            if (SearchBySkype != null)
            {
                page = 1;
            }
            else
            {
                SearchBySkype = currentFilter;
            }

            ViewBag.CurrentFilter = SearchByName;
            ViewBag.CurrentFilter = SearchByNumb;
            ViewBag.CurrentFilter = SearchByMail;
            ViewBag.CurrentFilter = SearchBySkype;

            var workers = from s in db.NTCWorkers select s;

            if (!String.IsNullOrEmpty(SearchByName))
            {
                workers = workers.Where(s => s.name_NTCworker.Contains(SearchByName));
            }

            if (!String.IsNullOrEmpty(SearchByNumb))
            {
                workers = workers.Where(s => s.phone_number_NTCworker.Contains(SearchByNumb));
            }

            if (!String.IsNullOrEmpty(SearchByMail))
            {
                workers = workers.Where(s => s.email_NTCworker.Contains(SearchByMail));
            }

            if (!String.IsNullOrEmpty(SearchBySkype))
            {
                workers = workers.Where(s => s.skype_NTCworker.Contains(SearchBySkype));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    workers = workers.OrderByDescending(s => s.name_NTCworker);
                    break;
                case "phone_numb":
                    workers = workers.OrderBy(s => s.phone_number_NTCworker);
                    break;
                case "phone_numb_desc":
                    workers = workers.OrderByDescending(s => s.phone_number_NTCworker);
                    break;
                case "email":
                    workers = workers.OrderBy(s => s.email_NTCworker);
                    break;
                case "email_desc":
                    workers = workers.OrderByDescending(s => s.email_NTCworker);
                    break;
                case "skype":
                    workers = workers.OrderBy(s => s.skype_NTCworker);
                    break;
                case "skype_desc":
                    workers = workers.OrderByDescending(s => s.skype_NTCworker);
                    break;
                case "experience":
                    workers = workers.OrderBy(s => s.experience);
                    break;
                case "experience_desc":
                    workers = workers.OrderByDescending(s => s.experience);
                    break;
                case "salary":
                    workers = workers.OrderBy(s => s.salary);
                    break;
                case "salary_desc":
                    workers = workers.OrderByDescending(s => s.salary);
                    break;
                default:
                    workers = workers.OrderBy(s => s.name_NTCworker);
                    break;
            }
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            return View(workers.ToPagedList(pageNumber, pageSize));
        }

        //Action для сторінки деталей
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NTCWorkers nTCWorkers = await db.NTCWorkers.FindAsync(id);
            if (nTCWorkers == null)
            {
                return HttpNotFound();
            }
            return View(nTCWorkers);
        }

        //Action-и для сторінки зі створення
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id_NTCworker,name_NTCworker,phone_number_NTCworker," +
            "email_NTCworker,skype_NTCworker,experience,salary")] NTCWorkers nTCWorkers)
        {
            if (ModelState.IsValid)
            {
                db.NTCWorkers.Add(nTCWorkers);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(nTCWorkers);
        }

        //Action-и для редагування
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NTCWorkers nTCWorkers = await db.NTCWorkers.FindAsync(id);
            if (nTCWorkers == null)
            {
                return HttpNotFound();
            }
            return View(nTCWorkers);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id_NTCworker,name_NTCworker,phone_number_NTCworker," +
            "email_NTCworker,skype_NTCworker,experience,salary")] NTCWorkers nTCWorkers)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nTCWorkers).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(nTCWorkers);
        }

        //Action-и для видалення
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NTCWorkers nTCWorkers = await db.NTCWorkers.FindAsync(id);
            if (nTCWorkers == null)
            {
                return HttpNotFound();
            }
            return View(nTCWorkers);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            NTCWorkers nTCWorkers = await db.NTCWorkers.FindAsync(id);
            db.NTCWorkers.Remove(nTCWorkers);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        //звільнення некерованих ресурсів
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

курсач/NTCService/NTCService/Views/NTCWorkers/Create.cshtml
@model NTCService.NTCWorkers

@{
    ViewBag.Title = "Створення";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Створити</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Інженер</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.name_NTCworker, "ПІБ", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name_NTCworker, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name_NTCworker, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.phone_number_NTCworker, "Тел", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.phone_number_NTCworker, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.phone_number_NTCworker, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.email_NTCworker, "Email", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.email_NTCworker, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.email_NTCworker, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.skype_NTCworker, "Skype ID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.skype_NTCworker, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.skype_NTCworker, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.experience, "Досвід", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.experience, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.experience, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.salary, "Ставка", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.salary, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.salary, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Cторити" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Повернутися до списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

курсач/NTCService/NTCService/Views/NTCWorkers/Delete.cshtml
@model NTCService.NTCWorkers

@{
    ViewBag.Title = "Видалення";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Видалити</h2>

<h3>Ви впевнені?</h3>
<div>
    <h4>Інженер</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("ПІБ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name_NTCworker)
        </dd>

        <dt>
            @Html.DisplayName("Тел")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone_number_NTCworker)
        </dd>

        <dt>
            @Html.DisplayName("Email")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email_NTCworker)
        </dd>

        <dt>
            @Html.DisplayName("Skype ID")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.skype_NTCworker)
        </dd>

        <dt>
            @Html.DisplayName("Досвід")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.experience)
        </dd>

        <dt>
            @Html.DisplayName("Ставка")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.salary)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Видалити" class="btn btn-default" /> |
        @Html.ActionLink("Повернутися до списку", "Index")
    </div>
    }
</div>

курсач/NTCService/NTCService/Views/NTCWorkers/Details.cshtml
@model NTCService.NTCWorkers

@{
    ViewBag.Title = "Деталі";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Деталі</h2>

<div>
    <h4>Інженер</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("ПІБ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name_NTCworker)
        </dd>

        <dt>
            @Html.DisplayName("Тел")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone_number_NTCworker)
        </dd>

        <dt>
            @Html.DisplayName("Email")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email_NTCworker)
        </dd>

        <dt>
            @Html.DisplayName("Skype ID")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.skype_NTCworker)
        </dd>

        <dt>
            @Html.DisplayName("Досвід")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.experience)
        </dd>

        <dt>
            @Html.DisplayName("Ставка")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.salary)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Редагувати", "Edit", new { id = Model.id_NTCworker }) |
    @Html.ActionLink("Повернутися до списку", "Index")
</p>

курсач/NTCService/NTCService/Views/NTCWorkers/Edit.cshtml
@model NTCService.NTCWorkers

@{
    ViewBag.Title = "Редагування";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Редагувати</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Інженер</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_NTCworker)

        <div class="form-group">
            @Html.LabelFor(model => model.name_NTCworker, "ПІБ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name_NTCworker, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name_NTCworker, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone_number_NTCworker, "Тел", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone_number_NTCworker, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone_number_NTCworker, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email_NTCworker, "Email", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email_NTCworker, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email_NTCworker, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.skype_NTCworker, "Skype ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.skype_NTCworker, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.skype_NTCworker, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.experience, "Досвід", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.experience, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.experience, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.salary, "Ставка", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.salary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.salary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Зберегти" class="btn btn-default" />
            </div>
        </div>
    </div>
}

    <div>
        @Html.ActionLink("Повернутися до списку", "Index")
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

курсач/NTCService/NTCService/Views/NTCWorkers/Index.cshtml
@model PagedList.IPagedList<NTCService.NTCWorkers>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Інженери";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Інженери</h2>

<p>
    @Html.ActionLink("Додати", "Create")
</p>

@using (Html.BeginForm("Index", "NTCWorkers", FormMethod.Get))
{
    <p>
        <strong>Пошук за ПІБ</strong>
        @Html.TextBox("SearchByName", ViewBag.CurrentFilter as string, new { @class = "form-control text-box single-line" })
    </p>
    <p>
        <strong>Пошук за тел.</strong>
        @Html.TextBox("SearchByNumb", ViewBag.CurrentFilter as string, new { @class = "form-control text-box single-line" })
    </p>
    <p>
        <strong>Пошук за Email</strong>
        @Html.TextBox("SearchByMail", ViewBag.CurrentFilter as string, new { @class = "form-control text-box single-line" })
    </p>
    <p>
        <strong>Пошук за Skype ID</strong>
        @Html.TextBox("SearchBySkype", ViewBag.CurrentFilter as string, new { @class = "form-control text-box single-line" })
    </p>
    <input type="submit" value="Знайти" class="btn btn-default" />
}
<br />

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("ПІБ", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Тел", "Index", new { sortOrder = ViewBag.PhoneNumbSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Email", "Index", new { sortOrder = ViewBag.EmailSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Skype ID", "Index", new { sortOrder = ViewBag.SkypeSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Досвід", "Index", new { sortOrder = ViewBag.ExperienceSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Ставка", "Index", new { sortOrder = ViewBag.SalarySortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name_NTCworker)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.phone_number_NTCworker)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.email_NTCworker)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.skype_NTCworker)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.experience)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.salary)
            </td>
            <td>
                @Html.ActionLink("Редагувати", "Edit", new { id = item.id_NTCworker }) |
                @Html.ActionLink("Деталі", "Details", new { id = item.id_NTCworker }) |
                @Html.ActionLink("Видалити", "Delete", new { id = item.id_NTCworker })
            </td>
        </tr>
    }

</table>
<br />
Сторінка @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) з @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))