курсач/NTCService/NTCService/Models/ModelDB/NTCServices.cs
namespace NTCService
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class NTCServices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NTCServices()
        {
            NTCJournal = new HashSet<NTCJournal>();
        }

        [Key]
        public int id_NTCservice { get; set; }

        [StringLength(50)]
        public string name_NTCservice { get; set; }

        public int? price_NTCservice { get; set; }

        public int id_NTCequipment { get; set; }

        public int id_type_NTCservice { get; set; }

        public virtual NTCequipmentInStock NTCequipmentInStock { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NTCJournal> NTCJournal { get; set; }

        public virtual TypesNTCServices TypesNTCServices { get; set; }
    }
}

курсач/NTCService/NTCService/Controllers/NTCServicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NTCService;
using PagedList;

namespace NTCService.Controllers
{
    [Authorize(Roles = "Admin")]

    //Клас NTCServicesController - для роботи з типами послуг
    public class NTCServicesController : Controller
    {
        private ModelDB db = new ModelDB();

        //Action для сторінки зі списком послуг
        public ActionResult Index(string sortOrder, string SearchByName, string SearchByTypeNTCService, string currentFilter, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.PriceSortParm = sortOrder == "price" ? "price_desc" : "price";
            ViewBag.TypeServiceSortParm = sortOrder == "name_type" ? "name_type_desc" : "name_type";
            ViewBag.EquipmentInStockrSortParm = sortOrder == "eq_in_stock" ? "eq_in_stock_desc" : "eq_in_stock";

            if (SearchByName != null)
            {
                page = 1;
            }
            else
            {
                SearchByName = currentFilter;
            }

            if (SearchByTypeNTCService != null)
            {
                page = 1;
            }
            else
            {
                SearchByTypeNTCService = currentFilter;
            }

            ViewBag.CurrentFilter = SearchByName;
            ViewBag.CurrentFilter = SearchByTypeNTCService;

            var services = db.NTCServices.Include(n => n.NTCequipmentInStock).Include(n => n.TypesNTCServices);

            if (!String.IsNullOrEmpty(SearchByName))
            {
                services = services.Where(s => s.name_NTCservice.Contains(SearchByName));
            }
            if (!String.IsNullOrEmpty(SearchByTypeNTCService))
            {
                services = services.Where(s => s.TypesNTCServices.name_type_NTCservice.Contains(SearchByTypeNTCService));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    services = services.OrderByDescending(s => s.name_NTCservice);
                    break;
                case "price":
                    services = services.OrderBy(s => s.price_NTCservice);
                    break;
                case "price_desc":
                    services = services.OrderByDescending(s => s.price_NTCservice);
                    break;
                case "name_type":
                    services = services.OrderBy(s => s.TypesNTCServices.name_type_NTCservice);
                    break;
                case "name_type_desc":
                    services = services.OrderByDescending(s => s.TypesNTCServices.name_type_NTCservice);
                    break;
                case "eq_in_stock":
                    services = services.OrderBy(s => s.NTCequipmentInStock.name_NTCequipment);
                    break;
                case "eq_in_stock_desc":
                    services = services.OrderByDescending(s => s.NTCequipmentInStock.name_NTCequipment);
                    break;
                default:
                    services = services.OrderBy(s => s.name_NTCservice);
                    break;
            }

            int pageSize = 8;
            int pageNumber = (page ?? 1);
            return View(services.ToPagedList(pageNumber, pageSize));
        }

        //Action для сторінки деталей
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NTCServices nTCServices = await db.NTCServices.FindAsync(id);
            if (nTCServices == null)
            {
                return HttpNotFound();
            }
            return View(nTCServices);
        }

        //Action-и для сторінки зі створення
        public ActionResult Create()
        {
            ViewBag.id_NTCequipment = new SelectList(db.NTCequipmentInStock, "id_NTCequipment", "name_NTCequipment");
            ViewBag.id_type_NTCservice = new SelectList(db.TypesNTCServices, "id_type_NTCservice", "name_type_NTCservice");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id_NTCservice,name_NTCservice,price_NTCservice,id_NTCequipment," +
            "id_type_NTCservice")] NTCServices nTCServices)
        {
            if (ModelState.IsValid)
            {
                db.NTCServices.Add(nTCServices);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.id_NTCequipment = new SelectList(db.NTCequipmentInStock, "id_NTCequipment", "name_NTCequipment", 
                nTCServices.id_NTCequipment);
            ViewBag.id_type_NTCservice = new SelectList(db.TypesNTCServices, "id_type_NTCservice", "name_type_NTCservice",
                nTCServices.id_type_NTCservice);
            return View(nTCServices);
        }

        //Action-и для редагування
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NTCServices nTCServices = await db.NTCServices.FindAsync(id);
            if (nTCServices == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_NTCequipment = new SelectList(db.NTCequipmentInStock, "id_NTCequipment", "name_NTCequipment", 
                nTCServices.id_NTCequipment);
            ViewBag.id_type_NTCservice = new SelectList(db.TypesNTCServices, "id_type_NTCservice", "name_type_NTCservice",
                nTCServices.id_type_NTCservice);
            return View(nTCServices);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id_NTCservice,name_NTCservice,price_NTCservice,id_NTCequipment," +
            "id_type_NTCservice")] NTCServices nTCServices)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nTCServices).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.id_NTCequipment = new SelectList(db.NTCequipmentInStock, "id_NTCequipment", "name_NTCequipment", 
                nTCServices.id_NTCequipment);
            ViewBag.id_type_NTCservice = new SelectList(db.TypesNTCServices, "id_type_NTCservice", "name_type_NTCservice", 
                nTCServices.id_type_NTCservice);
            return View(nTCServices);
        }

        //Action-и для видалення
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NTCServices nTCServices = await db.NTCServices.FindAsync(id);
            if (nTCServices == null)
            {
                return HttpNotFound();
            }
            return View(nTCServices);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            NTCServices nTCServices = await db.NTCServices.FindAsync(id);
            db.NTCServices.Remove(nTCServices);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        //звільнення некерованих ресурсів
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

курсач/NTCService/NTCService/Views/NTCServices/Create.cshtml
@model NTCService.NTCServices

@{
    ViewBag.Title = "Створення";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Створити</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Послуга</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.name_NTCservice, "Назва", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name_NTCservice, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name_NTCservice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.price_NTCservice, "Ціна, грн", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.price_NTCservice, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.price_NTCservice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.id_NTCequipment, "Обладнання", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("id_NTCequipment", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.id_NTCequipment, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.id_type_NTCservice, "Тип", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("id_type_NTCservice", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.id_type_NTCservice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Створити" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Повернутися до списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

курсач/NTCService/NTCService/Views/NTCServices/Delete.cshtml
@model NTCService.NTCServices

@{
    ViewBag.Title = "Видалення";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Видалити</h2>

<h3>Ви впевнені?</h3>
<div>
    <h4>Послуга</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Обладнання")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NTCequipmentInStock.name_NTCequipment)
        </dd>

        <dt>
            @Html.DisplayName("Тип")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypesNTCServices.name_type_NTCservice)
        </dd>

        <dt>
            @Html.DisplayName("Назва")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name_NTCservice)
        </dd>

        <dt>
            @Html.DisplayName("Ціна, грн")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price_NTCservice)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Видалити" class="btn btn-default" /> |
            @Html.ActionLink("Повернутися до списку", "Index")
        </div>
    }
</div>

курсач/NTCService/NTCService/Views/NTCServices/Details.cshtml
@model NTCService.NTCServices

@{
    ViewBag.Title = "Деталі";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Деталі</h2>

<div>
    <h4>Послуга</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Обладнання")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NTCequipmentInStock.name_NTCequipment)
        </dd>

        <dt>
            @Html.DisplayName("Тип")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypesNTCServices.name_type_NTCservice)
        </dd>

        <dt>
            @Html.DisplayName("Назва")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name_NTCservice)
        </dd>

        <dt>
            @Html.DisplayName("Ціна, грн")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price_NTCservice)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_NTCservice }) |
    @Html.ActionLink("Повернутися до списку", "Index")
</p>

курсач/NTCService/NTCService/Views/NTCServices/Edit.cshtml
@model NTCService.NTCServices

@{
    ViewBag.Title = "Редагування";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Редагувати</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Послуга</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_NTCservice)

        <div class="form-group">
            @Html.LabelFor(model => model.name_NTCservice, "Назва", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name_NTCservice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name_NTCservice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price_NTCservice, "Ціна, грн", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price_NTCservice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price_NTCservice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_NTCequipment, "Обладнання", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_NTCequipment", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_NTCequipment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_type_NTCservice, "Тип", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_type_NTCservice", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_type_NTCservice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Зберегти" class="btn btn-default" />
            </div>
        </div>
    </div>
}

    <div>
        @Html.ActionLink("Повернутися до списку", "Index")
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

курсач/NTCService/NTCService/Views/NTCServices/Index.cshtml
@model PagedList.IPagedList<NTCService.NTCServices>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Послуги";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Послуги</h2>

<p>
    @Html.ActionLink("Додати", "Create")
</p>

@using (Html.BeginForm("Index", "NTCServices", FormMethod.Get))
{
    <p>
        <strong>Пошук за назвою</strong>
        @Html.TextBox("SearchByName", ViewBag.CurrentFilter as string, new { @class = "form-control text-box single-line" })
    </p>
    <p>
        <strong>Пошук за типом</strong>
        @Html.TextBox("SearchByTypeNTCService", ViewBag.CurrentFilter as string, new { @class = "form-control text-box single-line" })
    </p>
    <input type="submit" value="Знайти" class="btn btn-default" />
}
<br />

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Назва", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Тип", "Index", new { sortOrder = ViewBag.TypeServiceSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Обладнання", "Index", new { sortOrder = ViewBag.EquipmentInStockrSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Ціна, грн", "Index", new { sortOrder = ViewBag.PriceSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name_NTCservice)              
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TypesNTCServices.name_type_NTCservice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NTCequipmentInStock.name_NTCequipment)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.price_NTCservice)
            </td>
            <td>
                @Html.ActionLink("Редагувати", "Edit", new { id = item.id_NTCservice }) |
                @Html.ActionLink("Деталі", "Details", new { id = item.id_NTCservice }) |
                @Html.ActionLink("Видалити", "Delete", new { id = item.id_NTCservice })
            </td>
        </tr>
    }

</table>
<br />
Сторінка @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) з @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))