курсач/NTCService/NTCService/Models/ModelDB/NTCClients.cs
namespace NTCService
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class NTCClients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NTCClients()
        {
            NTCJournal = new HashSet<NTCJournal>();
        }

        [Key]
        public int id_NTCclient { get; set; }

        [StringLength(50)]
        public string name_NTCclient { get; set; }

        [StringLength(30)]
        public string phone_number_NTCclient { get; set; }

        [StringLength(50)]
        public string email_NTCclient { get; set; }

        [StringLength(50)]
        public string skype_NTCclient { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NTCJournal> NTCJournal { get; set; }
    }
}

курсач/NTCService/NTCService/Controllers/NTCClientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NTCService;
using PagedList;

namespace NTCService.Controllers
{
    //Клас NTCClientsController - для роботи з типами техніки та ПЗ
    [Authorize(Roles = "Admin")]
    public class NTCClientsController : Controller
    {
        private ModelDB db = new ModelDB();

        //Action для сторінки зі клієнтів

        public ActionResult Index(string sortOrder, string SearchByName, string SearchByNumb, string SearchByMail, string SearchBySkype, 
            string currentFilter, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.PhoneNumbSortParm = sortOrder == "phone_numb" ? "phone_numb_desc" : "phone_numb";
            ViewBag.EmailSortParm = sortOrder == "email" ? "email_desc" : "email";
            ViewBag.SkypeSortParm = sortOrder == "skype" ? "skype_desc" : "skype";

            if (SearchByName != null)
            {
                page = 1;
            }
            else
            {
                SearchByName = currentFilter;
            }
            if (SearchByNumb != null)
            {
                page = 1;
            }
            else
            {
                SearchByNumb = currentFilter;
            }
            if (SearchByMail != null)
            {
                page = 1;
            }
            else
            {
                SearchByMail = currentFilter;
            }
            if (SearchBySkype != null)
            {
                page = 1;
            }
            else
            {
                SearchBySkype = currentFilter;
            }

            ViewBag.CurrentFilter = SearchByName;
            ViewBag.CurrentFilter = SearchByNumb;
            ViewBag.CurrentFilter = SearchByMail;
            ViewBag.CurrentFilter = SearchBySkype;

            var clients = from s in db.NTCClients select s;

            if (!String.IsNullOrEmpty(SearchByName))
            {
                clients = clients.Where(s => s.name_NTCclient.Contains(SearchByName));
            }

            if (!String.IsNullOrEmpty(SearchByNumb))
            {
                clients = clients.Where(s => s.phone_number_NTCclient.Contains(SearchByNumb));
            }

            if (!String.IsNullOrEmpty(SearchByMail))
            {
                clients = clients.Where(s => s.email_NTCclient.Contains(SearchByMail));
            }
            if (!String.IsNullOrEmpty(SearchBySkype))
            {
                clients = clients.Where(s => s.skype_NTCclient.Contains(SearchBySkype));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    clients = clients.OrderByDescending(s => s.name_NTCclient);
                    break;
                case "phone_numb":
                    clients = clients.OrderBy(s => s.phone_number_NTCclient);
                    break;
                case "phone_numb_desc":
                    clients = clients.OrderByDescending(s => s.phone_number_NTCclient);
                    break;
                case "email":
                    clients = clients.OrderBy(s => s.email_NTCclient);
                    break;
                case "email_desc":
                    clients = clients.OrderByDescending(s => s.email_NTCclient);
                    break;
                case "skype":
                    clients = clients.OrderBy(s => s.skype_NTCclient);
                    break;
                case "skype_desc":
                    clients = clients.OrderByDescending(s => s.skype_NTCclient);
                    break;
                default:
                    clients = clients.OrderBy(s => s.name_NTCclient);
                    break;
            }

            int pageSize = 8;
            int pageNumber = (page ?? 1);
            return View(clients.ToPagedList(pageNumber, pageSize));
        }

        //Action-и для сторінки зі створення
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id_NTCclient,name_NTCclient,phone_number_NTCclient," +
            "email_NTCclient,skype_NTCclient")] NTCClients nTCClients)
        {
            if (ModelState.IsValid)
            {
                db.NTCClients.Add(nTCClients);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(nTCClients);
        }

        //Action-и для редагування
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NTCClients nTCClients = await db.NTCClients.FindAsync(id);
            if (nTCClients == null)
            {
                return HttpNotFound();
            }
            return View(nTCClients);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id_NTCclient,name_NTCclient,phone_number_NTCclient," +
            "email_NTCclient,skype_NTCclient")] NTCClients nTCClients)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nTCClients).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(nTCClients);
        }

        //Action-и для видалення
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NTCClients nTCClients = await db.NTCClients.FindAsync(id);
            if (nTCClients == null)
            {
                return HttpNotFound();
            }
            return View(nTCClients);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            NTCClients nTCClients = await db.NTCClients.FindAsync(id);
            db.NTCClients.Remove(nTCClients);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        //звільнення некерованих ресурсів
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

курсач/NTCService/NTCService/Views/NTCClients/Create.cshtml
@model NTCService.NTCClients
@{
    ViewBag.Title = "Створення";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Створити</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Клієнт</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name_NTCclient, "ПІБ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name_NTCclient, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name_NTCclient, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone_number_NTCclient, "Тел", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone_number_NTCclient, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone_number_NTCclient, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email_NTCclient, "Email", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email_NTCclient, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email_NTCclient, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.skype_NTCclient, "Skype ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.skype_NTCclient, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.skype_NTCclient, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Створити" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Повернутися до списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

курсач/NTCService/NTCService/Views/NTCClients/Delete.cshtml
@model NTCService.NTCClients

@{
    ViewBag.Title = "Видалення";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Видалити</h2>

<h3>Ви впевнені?</h3>
<div>
    <h4>Клієнт</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("ПІБ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name_NTCclient)
        </dd>

        <dt>
            @Html.DisplayName("Тел")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone_number_NTCclient)
        </dd>

        <dt>
            @Html.DisplayName("Email")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email_NTCclient)
        </dd>

        <dt>
            @Html.DisplayName("Skype ID")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.skype_NTCclient)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Видалити" class="btn btn-default" /> |
            @Html.ActionLink("Повернутися до списку", "Index")
        </div>
    }
</div>

курсач/NTCService/NTCService/Views/NTCClients/Details.cshtml
@model NTCService.NTCClients

@{
    ViewBag.Title = "Деталі";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Деталі</h2>

<div>
    <h4>Клієнт</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("ПІБ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name_NTCclient)
        </dd>

        <dt>
            @Html.DisplayName("Тел")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone_number_NTCclient)
        </dd>

        <dt>
            @Html.DisplayName("Email")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email_NTCclient)
        </dd>

        <dt>
            @Html.DisplayName("Skype ID")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.skype_NTCclient)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Редагувати", "Edit", new { id = Model.id_NTCclient }) |
    @Html.ActionLink("Повернутися до списку", "Index")
</p>

курсач/NTCService/NTCService/Views/NTCClients/Edit.cshtml
@model NTCService.NTCClients

@{
    ViewBag.Title = "Редагування";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Редагувати</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Клієнт</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_NTCclient)

        <div class="form-group">
            @Html.LabelFor(model => model.name_NTCclient, "ПІБ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name_NTCclient, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name_NTCclient, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone_number_NTCclient, "Тел", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone_number_NTCclient, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone_number_NTCclient, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email_NTCclient, "Email", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email_NTCclient, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email_NTCclient, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.skype_NTCclient, "Skype ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.skype_NTCclient, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.skype_NTCclient, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Зберегти" class="btn btn-default" />
            </div>
        </div>
    </div>
}

    <div>
        @Html.ActionLink("Повернутися до списку", "Index")
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

курсач/NTCService/NTCService/Views/NTCClients/Index.cshtml
@model PagedList.IPagedList<NTCService.NTCClients>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Клієнти";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 align="center">Клієнти</h2>

<p>
    @Html.ActionLink("Додати", "Create")
</p>

@using (Html.BeginForm("Index", "NTCClients", FormMethod.Get))
{
    <p>
        <strong>Пошук за ПІБ</strong>
        @Html.TextBox("SearchByName", ViewBag.CurrentFilter as string, new { @class = "form-control text-box single-line" })
    </p>
    <p>
        <strong>Пошук за тел.</strong>
        @Html.TextBox("SearchByNumb", ViewBag.CurrentFilter as string, new { @class = "form-control text-box single-line" })
    </p>
    <p>
        <strong>Пошук за Email</strong>
        @Html.TextBox("SearchByMail", ViewBag.CurrentFilter as string, new { @class = "form-control text-box single-line" })
    </p>
    <p>
        <strong>Пошук за Skepe ID</strong>
        @Html.TextBox("SearchBySkype", ViewBag.CurrentFilter as string, new { @class = "form-control text-box single-line" })
    </p>
    <input type="submit" value="Знайти" class="btn btn-default" />
}
<br />

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("ПІБ", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Тел", "Index", new { sortOrder = ViewBag.PhoneNumbSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Email", "Index", new { sortOrder = ViewBag.EmailSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Skype ID", "Index", new { sortOrder = ViewBag.SkypeSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name_NTCclient)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.phone_number_NTCclient)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.email_NTCclient)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.skype_NTCclient)
            </td>
            <td>
                @Html.ActionLink("Редагувати", "Edit", new { id = item.id_NTCclient }) |
                @Html.ActionLink("Деталі", "Details", new { id = item.id_NTCclient }) |
                @Html.ActionLink("Видалити", "Delete", new { id = item.id_NTCclient })
            </td>
        </tr>
    }

</table>

<br />
Сторінка @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) з @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))